server:
  port: 9527

#eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instance-id: zuul9527.com #修改eureka上默认的描述信息
      prefer-ip-address: true

spring:
  application:
    name: springcloud-zuul

#info配置
info:
  app.name: jia-springcloud
  company.name: blog.jiastudy.com

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  #  ignored-services: springcloud-provider-dept  #不能在使用这个路径访问了
  ignored-services: springcloud-provider-dept  #隐藏全部的
  prefix: /jia  #设置公共的前缀